In [ ]:
#1
import numpy as np
empty_array = np.empty((2,2))
print("empty array 2x2:\n",empty_array)
#Initializes an all onee array with size 4x2.
ones_array = np.ones((4,2))
print("all one array 4x2:\n",ones_array)
#Return a new array of given shape and type, filled with fill value
fill_value = 7
shape =(3,3)
filled_array = np.full(shape,fill_value)
print ("filled array 3x3:n",filled_array)
#Return a new array of zeros with same shape and type as a given array
zeros_array=np.zeros_like(filled_array)
print("xeros array 3x3:\n",zeros_array)
#Return a  new array of one with same shape and type as a given array
ones_array = np.ones_like (filled_array)
print("ones array 3x3:\n",ones_array)
#For an existing list new_list =[1,2,3,4] convert to an numpy array
new_list = [1,2,3,4]
numpy_array= np.array(new_list)
print("numpy array:",numpy_array)


empty array 2x2:
 [[-65.4375  -4.    ]
 [ 65.4375  16.    ]]
all one array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
filled array 3x3:n [[7 7 7]
 [7 7 7]
 [7 7 7]]
xeros array 3x3:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
ones array 3x3:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
numpy array: [1 2 3 4]


In [ ]:
#2
import numpy as np
###Create an array with values ranging from 10 to 49
array_range = np.arange(10,50)
print("Array with value ranging from 10 to 49:\n",array_range)
#Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3,3)





print("\n3x3 Matrix with values ranging from 0 to 8:\n",matrix_3x3)
###Create a 3x3 identity matrix
identity_matrix=np.eye(3)
print("\n3x3 Identity Matrix:\n",identity_matrix)
###Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n",random_array)
print("Mean of the array:",mean_value)
#Create a 10x10 array with random vaalues and find the min and max
random_matrix = np.random.random((10,10))
min_value= random_matrix.min()
mix_value = random_matrix.max()
print("\n10x10 Array with random values:\n",random_matrix)
print("Minimium value:",min_value)
print("Maximum value:",mix_value)
#Create a zero array of size 10 and replace 5th element with 1.
array0=np.zeros(10)
array0[4]=1
print("\nZero Array of size 10 with 5th element replaced by1:\n",array0)
#Reverse an array arr=[1,2,0,0,4,0].
arr = np.array([1,2,0,0,4,0])
reversed_arr= arr[::-1]
print("\nReversed Array:",reversed_arr)
#Create a 2d array with 1 on border and 0 inside
arr_2d = np.ones((5,5))
arr_2d=np.ones((5,5))
arr_2d[1:-1,1:-1]=0
print("\n2D Array with 1 on border and 0 inside:\n",arr_2d)
##Create a 8x8 matrix and fill it with a checkerboard pattern.
checkerboard=np.zeros((8,8),dtype=int)
checkerboard [1::2, ::2]=1
checkerboard[::2, 1::2]=1
print("\n8x8 Checkerboard Matrix:\n",checkerboard)




Array with value ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.14761518 0.51722171 0.61013244 0.10192616 0.12901927 0.00868994
 0.09437119 0.09156947 0.23986023 0.15209274 0.88878455 0.52985876
 0.28348831 0.42668637 0.91509487 0.70087643 0.79632703 0.86418951
 0.72630191 0.64084074 0.85359855 0.06136543 0.44262282 0.75553817
 0.31759442 0.8819558  0.97504986 0.80582612 0.40742337 0.42907891]
Mean of the array: 0.4931666758968371

10x10 Array with random values:
 [[0.06387011 0.49518588 0.2826675  0.16271138 0.09123666 0.22311176
  0.51891374 0.25475952 0.57806916 0.17597512]
 [0.863428   0.81520694 0.10626925 0.15057586 0.90207737 0.38510659
  0.47066535 0.98028226 0.82841399 0.02701648]
 [0.00762402 0.41834338 0.58317607 0.

In [ ]:
#3
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#Add the two arrays


add_arrays = x+y
print("Addition of x an y :\n",add_arrays)
#Subtract the two arrays
sub_arrays = x-y
print ("\nSubtraction of x and y :\n",sub_arrays)
#Muktiply the array with any integer (choosing 3)

multiply_x = x * 3
print("\nMultiplication of x with 3:\n",multiply_x)
#Find the square of each element of the array
square_x = np.square(x)
print("\nSquare of each element in x:\n",square_x)
#Find the dot product
#Dot product of v and w
dot_vw = np.dot(v,w)
print ("\nDot product of v and w:", dot_vw)
#Dot product of x and v
dot_xv = np.dot(x,v)
print("Dot product of x and v:\n",dot_xv)
#Dot product of x and y
dot_xy = np.dot(x, y)
print("Dot product of x and y:\n",dot_xy)
#Concatenate x and y along rows; concatenate v and w along columns
concat_xy_row = np.concatenate((x,y), axis=0)
concat_vw_column = np.vstack((v,w))
print ("\nConcatenation of x and y along rows:\n",concat_xy_row)
print("Concatenation of v and w along columns:\n",concat_vw_column)
#Concatenation x and v; observe the error
try:
 concat_xv = np.concatenate ((x,v),axis=0)
 print("\nConcatenation of x and v:\n",concat_xv)
except ValueError as e:
 print("\nError when concatenating x and v:")
 print (e)



Addition of x an y :
 [[ 6  8]
 [10 13]]

Subtraction of x and y :
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
import numpy as np
import time

# 1. Element-wise Addition
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]
arr1 = np.array(list1)
arr2 = np.array(list2)

# Python Lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print("Time taken for element-wise addition using Python Lists: ", end_time - start_time, "seconds\n")

# NumPy Arrays
start_time = time.time()
array_sum = arr1 + arr2
end_time = time.time()
print("Time taken for element-wise addition using NumPy Arrays: ", end_time - start_time, "seconds\n")

# 2. Element-wise Multiplication
# Python Lists
start_time = time.time()
list_prod = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
print("Time taken for element-wise multiplication using Python Lists: ", end_time - start_time, "seconds\n")

# NumPy Arrays
start_time = time.time()
array_prod = arr1 * arr2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy Arrays: ", end_time - start_time, "seconds\n")

# 3. Dot Product
# Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
print("Time taken for dot product using Python Lists: ", end_time - start_time, "seconds\n")

# NumPy Arrays
start_time = time.time()
dot_product_array = np.dot(arr1, arr2)
end_time = time.time()
print("Time taken for dot product using NumPy Arrays: ", end_time - start_time, "seconds\n")

# 4. Matrix Multiplication
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]
numpy_matrix1 = np.array(matrix1)
numpy_matrix2 = np.array(matrix2)

# Python Lists
start_time = time.time()
matrix_result = [[sum(a * b for a, b in zip(matrix1_row, matrix2_col)) for matrix2_col in zip(*matrix2)] for matrix1_row in matrix1]
end_time = time.time()
print("Time taken for matrix multiplication using Python Lists: ", end_time - start_time, "seconds\n")

# NumPy Arrays
start_time = time.time()
numpy_matrix_result = np.dot(numpy_matrix1, numpy_matrix2)
end_time = time.time()
print("Time taken for matrix multiplication using NumPy Arrays: ", end_time - start_time, "seconds\n")



Time taken for element-wise addition using Python Lists:  0.14765095710754395 seconds

Time taken for element-wise addition using NumPy Arrays:  0.008084297180175781 seconds

Time taken for element-wise multiplication using Python Lists:  0.17162537574768066 seconds

Time taken for element-wise multiplication using NumPy Arrays:  0.005540609359741211 seconds

Time taken for dot product using Python Lists:  0.2047290802001953 seconds

Time taken for dot product using NumPy Arrays:  0.002120494842529297 seconds

Time taken for matrix multiplication using Python Lists:  199.22744274139404 seconds

Time taken for matrix multiplication using NumPy Arrays:  1.7887771129608154 seconds



In [7]:
#4
import numpy as np
import time

#1. Element - wise Addition
list1 = [i for i in range (1000000)]
list2 = [i for i in range (1000000)]
arr1=np.array(list1)
arr2=np.array(list2)

#Python Lists
start_time=time.time()
list_sum=[list1[i]+list2[i] for i in range (len(list1))]
end_time=time.time()
print("Time taken for element-wise addition using Python Lists:",end_time-start_time,"seconds\n")
#Numpy Arrays
start_time=time.time()
array_sum=arr1+arr2
end_time+time.time()
print("Time taken for element-wise addition using NumPy Arrays:",end_time-start_time,"seconds\n")

#2.Element-wise Multiplication
#Python Lists
start_time=time.time()
list_prod=[list1[i]*list2[i] for i in range (len(list1))]
end_time= time.time()
print("Time taken for element-wise multiplication using Python Lists:",end_time-start_time,"seconds\n")

#Numpy Arrays
start_time=time.time()
array_prod=arr1*arr2
end_time=time.time()
print("Time taken for element-wise multiplication using NumPy Arrays:",end_time-start_time,"seconds\n")

#3.Dot Product
#Python Lists
start_time=time.time()
dot_product_list=sum(list1[i]*list2[i] for i in range (len(list1)))

end_time=time.time()
print("Time taken for dot product using Python Lists:",end_time-start_time,"seconds\n")

#NumPy Arrays
start_time+time.time()
dot_product_array=np.dot(arr1,arr2)
end_time=time.time()
print("Time taken for dot product using NumPy Arrays:",end_time-start_time,"seconds\n")

#4.Matrix Multiplication
matrix1=[[i for i in range (1000)]for j in range(1000)]
matrix2=[[i for i in range (1000)] for j in range (1000)]
numpy_matrix1=np.array(matrix1)
numpy_matrix2 = np.array(matrix2)
#Python Lists
start_time=time.time()
matrix_result=[[sum(a*b for a,b in zip(matrix1_row,matrix2_col)) for matrix2_col in zip (*matrix2)] for matrix1_row in matrix1]
end_time == time.time()
print ("Time taken for matrix multiplication using Python Lists:",end_time-start_time,"seconds\n")

#NumPy Arrays
start_time = time.time()
numpy_matrix_result = np.dot(numpy_matrix1, numpy_matrix2)
numpy_matrix_result = np.dot(numpy_matrix1,numpy_matrix2)

end_time=time.time()
print("Time taken for matrix multiplication using Numpy Arrays:",end_time-start_time,"seconds\n")


Time taken for element-wise addition using Python Lists: 0.1661977767944336 seconds

Time taken for element-wise addition using NumPy Arrays: -0.0021829605102539062 seconds

Time taken for element-wise multiplication using Python Lists: 0.15149211883544922 seconds

Time taken for element-wise multiplication using NumPy Arrays: 0.0027632713317871094 seconds

Time taken for dot product using Python Lists: 0.16631627082824707 seconds

Time taken for dot product using NumPy Arrays: 0.16892170906066895 seconds

Time taken for matrix multiplication using Python Lists: -0.26007986068725586 seconds

Time taken for matrix multiplication using Numpy Arrays: 3.773691415786743 seconds

